sudo: false
language: node_js
node_js:
  - 6
  - node
notifications:
  slack:
    secure: H7kOv9XJ70UUMd+j2V/DgmFV4bjBmOanFkHu8bloBrAcSOex0kE/mFQI4ysNRMORBTuWETFs9L+ilVLMHakFmF29043MIu/XGdK0hUNZypwNDsZyIPYQwQn6qbQ+Lyw4VFJLW7/myNwSJzTxUDUSgCI4dwCWz34CljVSLS/Yw30=
branches:
  only:
    - v2.x.x
    - master
    - develop
    - /^hotfix-.*$/
cache:
  directories:
    - node_modules
